### ISSUE TITLE
Missing Header in the Umbrella Header for macOS

### ISSUE THREAD

**Issue by ronak2121** [CocoaLumberjack/CocoaLumberjack#783]
### New Issue Checklist
- [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
- [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | macos |
| Platform Version | 10.11 |
| CocoaLumberjack Version | 3.0 |
| Integration Method | manually |
| Xcode Version | Xcode 8 |
| Repro rate | all the time (100%) |
| Demo project link | NA |
### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

Getting this while on macOS. Seems like you forgot to add this header on macOS to the umbrella header.

<module-includes>:1:1: Umbrella header for module 'CocoaLumberjack' does not include header 'CLIColor.h'

When can this be fixed?

**Comment by max-potapov** [comment]
PR #781

**Comment by ronak2121** [comment]
Any ETA on when a fix for this will be released?

**Comment by bpoplauschi** [comment]
Fixed by #781. Will release 3.1.0 soon
