### ISSUE TITLE
Umbrella header for module 'CocoaLumberjack' does not include header 'CocoaLumberjack.common-umbrella.h'

### ISSUE THREAD

**Issue by arifken** [CocoaLumberjack/CocoaLumberjack#815]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [X] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

Hello! I'm getting a compile error when trying to use CocoaLumberjack in a WatchKit Extension (WatchOS 1.0, unfortunately). For some reason, it was working in version 2.3.0 of CocoaLumberjack, but in version 3.0.x I get the following compile error:

[project path]/<module-includes>:1:1: Umbrella header for module 'CocoaLumberjack' does not include header 'CocoaLumberjack.common-umbrella.h'

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios / watchos
 Platform Version        | 10.1
 CocoaLumberjack Version | 3.0.0
 Integration Method      | cocoapods
 Xcode Version           | e.g. Xcode 8.1
 Repro rate              | 100% of the time

### Issue Description and Steps

[project path]/<module-includes>:1:1: Umbrella header for module 'CocoaLumberjack' does not include header 'CocoaLumberjack.common-umbrella.h'

This error only seems to come up when I do an Archive. If i just build/run the same configuration it works. Any ideas?

Thanks!

### UPDATE:

I was able to work around the issue by adding these two lines back into CocoaLumberjack.podspec:

```
s.public_header_files = 'Classes/*.h'

s.module_map = 'Framework/Lumberjack/CocoaLumberjack.modulemap'
```

**Comment by sushichop** [comment]
@arifken 

Hi! Could you try to use master branch? 
```
target 'YourTarget' do 
  use_frameworks!
  pod 'CocoaLumberjack', :git => 'git@github.com:CocoaLumberjack/CocoaLumberjack.git'
end
```
As far as I understand, the podspec of CocoaLumberjack 3.0.0 has problem about umbrella header.
It doesn't work properly especially when you use Objective-C.

[Note]
Before you try again, maybe you should clear CocoaPods cache files.
**Take care not to remove other files.** 😉
```
$ rm -rf ${YOUR_WORK_DIR}/Pods
$ rm -rf ~/Library/Developer/Xcode/DerivedData/*
$ rm -rf ~/Library/Caches/CocoaPods
```

I hope this will help you.

**Comment by arifken** [comment]
Thanks @sushichop! So, I just tried it again off master after clearing DerivedData, Pods, and cocoapods caches, and unfortunately no luck. I'm getting the same error:

/Users/.../<module-includes>:1:1: Umbrella header for module 'CocoaLumberjack' does not include header 'CocoaLumberjack-umbrella.h'

For some reason, specifying the module map in the cocoapods spec seems to fix it... but I still can't seem to figure out why. Do you know what the reason was for removing these two lines from the podspec?

```
s.public_header_files = 'Classes/*.h'
s.module_map = 'Framework/Lumberjack/CocoaLumberjack.modulemap'
```

**Comment by sushichop** [comment]
@arifken thanks for trying it! Umm, master branch still seems to have problem...

> Do you know what the reason was for removing these two lines from the podspec?

These two lines was removed by this commit( https://github.com/CocoaLumberjack/CocoaLumberjack/commit/0f5a793843c748c06511e5c3d1e20967798b50d1). 
The reason is probably to erase the error by `pod lib lint`, but I think this is just a temporizing solution.
The best solution is to fix this error properly even when CocoaLumberjck uses custom modulemap.

IMO, this bug should be fixed by setting each header file correctly at each framework's target.
If I have a time in the weekend(or next week?), I'll try it.

**Comment by sushichop** [comment]
I tried above. I actually achieved `pod lib lint` pass even when you modumap file by changing podspec and access level of CLIColor.h, etc. 
However I encountered other errors when I ran travis-ci test 😥
To solve this issue, more time or another solution may need...

**Comment by sushichop** [comment]
UPDATE INFO:

I found that CocoaLumberjack and CocoaLumberjackSwift target support all platforms **except watchOS**. 
So I made these targets support all platforms **including watchOS**. See PR: #818.

It does not actually use modulemap file, but I hope it will fix the issue about watchOS.

**Comment by arifken** [comment]
Nice catch on watchOS! Definitely needed for watchOS 2.0+... I think watchOS 1.0 is a different configuration, as far as how the "platform" is defined. I will also try and take a look at the modulemap issue and see if I can help out on that.

**Comment by sushichop** [comment]
I made a PR that enables modulemap feature again as CocoaLumberjack used it (e.g. CocoaLumberjack 2.3.0). 
See #824 for detail.

**Comment by bpoplauschi** [comment]
@sushichop can we consider this issue fixed?

**Comment by sushichop** [comment]
@bpoplauschi 
Basically, yes. Originally Cocoalumberjack  did not support CocoaPods integration with watchOS. Now you can integrate watchOS project with CocoaPods. I confirmed I was able to integrate watchOS 2.0 with iOS 9.0 at least.

But watchOS 2.0 or later may be required definitely like many other libraries does.
In addition, watchOS 2.0 or later simulators are only bundled with the latest Xcode(8.0 or later) and I don't have AppleWatch(device) that supports watchOS 1.0.

**Comment by bpoplauschi** [comment]
Thanks @sushichop
